### ISSUE TITLE
HTML files in sub-modules cause 404 in dist build

### ISSUE THREAD

**Issue by matthewhegarty** [Anjmao/angular2-production-workflow#2]
I've found this doesn't handle HTML files in sub-modules.  Reproduced [here](https://github.com/matthewhegarty/angular2-production-workflow/tree/sub-module-html-causes-404).

When run using `npm run start` you can see the sub-module HTML included, but after running `npm run dist`, and then serving files from the `dist` directory, you will see 404 for the sub-module HTML.

**Comment by digitalcraftco** [comment]
If you are bundling the html templates you need to use the text plugin for this repo. This bundles the html with Systemjs. I have found it works for me.

`templateUrl: 'app/sub-module/sub-module.component.html'`

change to:

`template: require('sub-module.component.html!text')
`
